openapi: 3.0.3
info:
  title: Rosanix API
  description: Rosanix API es una API RESTful diseñada para gestionar tareas de manera eficiente. Permite a los usuarios crear, leer, actualizar y eliminar tareas mediante un sistema fácil de usar y seguro. La API está estructurada en torno a la autenticación basada en JSON Web Tokens (JWT), lo que garantiza que solo los usuarios autenticados puedan acceder a sus datos personales y realizar operaciones sobre sus tareas.
  version: 1.0.0

servers:
  - url: http://localhost:4000/api
    description: Servidor local de desarrollo

tags:
  - name: Auth
    description: "Endpoints relacionados con la autenticación y la gestión de sesiones."
  - name: Usuarios
    description: "Operaciones relacionadas con la gestión de los usuarios."
  - name: Tareas
    description: "Operaciones CRUD para tareas de usuario."
  - name: Admin
    description: "Endpoints restringidos a administradores para gestión interna."

components:
  schemas:
    Tareas:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          maxLength: 30
          example: "Tarea title"
        descr:
          type: string
          example: "tarea description"
        createdAt:
          type: string
          format: date-time
          readOnly: true
          example: "2017-07-21T17:32:28Z"
        expiresIn:
          type: string
          format: date-time
          example: "2017-07-21T17:32:28Z"
        state:
          type: string
          enum: ["pendiente", "completada"]
          example: "pendiente"
        priority:
          type: string
          enum: ["baja", "media", "alta"]
          example: "media"
        userId:
          type: integer
          example: 1
      required:
        - title

    Usuarios:
      properties:
        id:
          type: integer
          example: 1
        name:
          type: string
          minLength: 3
          maxLength: 30
          example: "John Doe"
        email:
          type: string
          format: email
          maxLength: 100
          example: "johndoe@email.com"
        passw:
          type: string
          format: password
          minLength: 8
          writeOnly: true
          example: "password123"
        role:
          type: string
          enum: ["admin", "usuario"]
          example: "usuario"
        createdAt:
          type: string
          format: date-time
          readOnly: true
          example: "2017-07-21T17:32:28Z"
        active:
          type: boolean
          example: true
        codeEmail:
          type: string
          format: uuid
          example: "444792de-1209-4ffb-96fc-956012baaf9e"
      required:
        - name
        - email
        - passw

  securitySchemes:
    JWTAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: "El token JWT se envía en una cookie llamada `access_token`."
  security:
    - JWTAuth: []

paths:
  /api/login:
    post:
      tags:
        - Auth
      summary: Iniciar sesión en la aplicación
      requestBody:
        required: true
        content:
          application/json:
            example:
              email: "email@email.com"
              passw: "password123"
      responses:
        "200":
          description: Inicio de sesión exitoso
          content:
            application/json:
              example:
                name: "John Doe"
                email: "email@mail.com"
                role: "usuario"
                createdAt: "2024-11-10T12:00:00Z"
                active: true
        "400":
          description: Credenciales Invalidas
        "500":
          description: Error del servidor
  /api/register:
    post:
      tags:
        - Auth
      summary: Registrate en la aplicación
      requestBody:
        required: true
        content:
          application/json:
            example:
              name: "John Doe"
              email: "email@email.com"
              passw: "password123"
      responses:
        "200":
          description: Registro realizado con éxito
          content:
            application/json:
              example:
                name: "John Doe"
                email: "email@mail.com"
                role: "usuario"
                createdAt: "2024-11-10T12:00:00Z"
                active: false
        "400":
          description: Cuenta ya registrada
        "500":
          description: Error del servidor
  /api/logout:
    post:
      tags:
        - Auth
      summary: Cierra la sesión
      responses:
        "204":
          description: Cierre de sesión realizado con éxito
  /api/forgotpass:
    post:
      tags:
        - Auth
      summary: Envia un código al correo para habilitar el reseteo de la contraseña
      responses:
        "204":
          description: Código enviado
  /api/testcode:
    post:
      tags:
        - Auth
      summary: Valida que el código enviado al correo sea el mismo que el proporcionado por el usuario en su intento de resetear la contraseña
      responses:
        "204":
          description: Código validado
        "400":
          description: Código incorrecto
  /api/resetpass:
    post:
      tags:
        - Auth
      summary: Realiza el cambio de contraseña anterior olvidada por la nueva
      responses:
        "204":
          description: Contraseña cambiada
  /api/auth/verify-token:
    get:
      tags:
        - Auth
      summary: Verifica que tanto el token sea válido como que contenga un usuario real
      responses:
        "200":
          description: Token verificado y usuario real
          content:
            application/json:
              example:
                name: "John Doe"
                email: "email@mail.com"
                role: "usuario"
                createdAt: "2024-11-10T12:00:00Z"
                active: true
        "401":
          description: Token faltante
        "403":
          description: No autorizado
        "498":
          description: Token inválido
  /api/tasks:
    get:
      tags:
        - Tareas
      summary: Obtener todas las tareas del usuario
      security:
        - JWTAuth: []
      responses:
        "200":
          description: Lista de tareas
          content:
            application/json:
              example:
                id: 1
                title: "Nueva Tarea"
                descr: "Descripción de la tarea"
                createdAt: "2024-11-10T12:00:00Z"
                expiresIn: "2024-11-10T12:00:00Z"
                state: "pendiente"
                priority: "media"
                userId: 1
        "401":
          description: No autorizado
        "403":
          description: Su cuenta se encuentra inactiva
        "404":
          description: Sin tareas creadas
        "498":
          description: Token inválido

    post:
      tags:
        - Tareas
      summary: Crear una nueva tarea
      security:
        - JWTAuth: []
      requestBody:
        required: true
        content:
          application/json:
            example:
              title: "Nueva Tarea"
              descr: "Descripción de la tarea"
              expiresIn: "2024-11-10T12:00:00Z"
              priority: "media"
      responses:
        "200":
          description: Tarea creada
          content:
            application/json:
              example:
                id: 1
                title: "Nueva Tarea"
                descr: "Descripción de la tarea"
                createdAt: "2024-11-10T12:00:00Z"
                expiresIn: "2024-11-10T12:00:00Z"
                state: "pendiente"
                priority: "media"
                userId: 1
        "401":
          description: No autorizado
        "403":
          description: Su cuenta se encuentra inactiva
        "498":
          description: Token inválido
        "500":
          description: Error del servidor

  /api/tasks/{id}:
    get:
      tags:
        - Tareas
      summary: Obtener datos de una tarea específica
      security:
        - JWTAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: "ID único de la tarea"
          schema:
            type: integer
      responses:
        "200":
          description: Datos de la tarea
          content:
            application/json:
              example:
                id: 1
                title: "Nueva Tarea"
                descr: "Descripción de la tarea"
                createdAt: "2024-11-10T12:00:00Z"
                expiresIn: "2024-11-10T12:00:00Z"
                state: "pendiente"
                priority: "media"
                userId: 1
        "401":
          description: No autorizado
        "403":
          description: Su cuenta se encuentra inactiva
        "404":
          description: Tarea no encontrada
        "498":
          description: Token inválido

    put:
      tags:
        - Tareas
      summary: Modificar datos de una tarea
      security:
        - JWTAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID de la tarea a actualizar
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            example:
              title: "Tarea Actualizada"
              descr: "Descripción de la tarea actualizada"
              expiresIn: "2024-11-10T12:00:00Z"
              priority: "media"
      responses:
        "200":
          description: Tarea actualizada con éxito
          content:
            application/json:
              example:
                id: 1
                title: "Nueva Tarea"
                descr: "Descripción de la tarea"
                createdAt: "2024-11-10T12:00:00Z"
                expiresIn: "2024-11-10T12:00:00Z"
                state: "pendiente"
                priority: "media"
                userId: 1
        "401":
          description: No autorizado
        "403":
          description: Su cuenta se encuentra inactiva
        "404":
          description: Tarea no encontrada
        "498":
          description: Token inválido
        "500":
          description: Error del servidor

    patch:
      tags:
        - Tareas
      summary: Marcar como completada una tarea
      security:
        - JWTAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Tarea actualizada
          content:
            application/json:
              example:
                id: 1
                title: "Nueva Tarea"
                descr: "Descripción de la tarea"
                createdAt: "2024-11-10T12:00:00Z"
                expiresIn: "2024-11-10T12:00:00Z"
                state: "pendiente"
                priority: "media"
                userId: 1
        "401":
          description: No autorizado
        "403":
          description: Su cuenta se encuentra inactiva
        "404":
          description: Tarea no encontrada
        "498":
          description: Token inválido
        "500":
          description: Error del servidor

    delete:
      tags:
        - Tareas
      summary: Borrar una tarea
      security:
        - JWTAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Tarea eliminada con éxito
        "401":
          description: No autorizado
        "403":
          description: Su cuenta se encuentra inactiva
        "404":
          description: Tarea no encontrada
        "498":
          description: Token inválido
        "500":
          description: Error del servidor

  /api/confirm-account/{uuid}:
    get:
      tags:
        - Usuarios
      summary: Confirmar email
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "301":
          description: Redirección al front
        "404":
          description: Usuario no encontrado
        "500":
          description: Error del servidor

  /api/change-email/{userId}/{newEmail}:
    get:
      tags:
        - Usuarios
      summary: Cambiar email
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
        - name: newEmail
          in: path
          required: true
          schema:
            type: string
      responses:
        "301":
          description: Redirección al front
        "404":
          description: Usuario no encontrado
        "500":
          description: Error del servidor

  /api/user:
    put:
      tags:
        - Usuarios
      summary: Modificar nombre y/o email
      security:
        - JWTAuth: []
      parameters:
        - name: id
          in: header
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            example:
              name: "John Doe"
              email: "johndoe@email.com"
      responses:
        "200":
          description: Usuario actualizado
          content:
            application/json:
              example:
                name: "John Doe"
                email: "johndoe@email.com"
                role: "usuario"
                createdAt: "2024-11-10T12:00:00Z"
        "403":
          description: Su cuenta se encuentra inactiva
        "404":
          description: Usuario no encontrado
        "500":
          description: Error del servidor

  /api/user/change-password:
    put:
      tags:
        - Usuarios
      summary: Cambiar contraseña
      security:
        - JWTAuth: []
      parameters:
        - name: id
          in: header
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            example:
              currentPassw: "password123"
              newPassw: "newPassword123"
      responses:
        "200":
          description: Contraseña cambiada exitosamente
        "403":
          description: Su cuenta se encuentra inactiva
        "400":
          description: Contraseña incorrecta La contraseña actual no coincide con la registrada.
        "500":
          description: Error del servidor

  /api/admin/users:
    get:
      tags:
        - Admin
      summary: Obtener todos los usuarios
      security:
        - JWTAuth: []
      responses:
        "200":
          description: Lista de Usuarios
          content:
            application/json:
              example:
                name: "John Doe"
                email: "johndoe@email.com"
                role: "usuario"
                createdAt: "2024-11-10T12:00:00Z"
        "403":
          description: No autorizado
        "404":
          description: No existen usuarios
        "500":
          description: Error del servidor

    post:
      tags:
        - Admin
      summary: Crea un usuario
      security:
        - JWTAuth: []
      requestBody:
        required: true
        content:
          application/json:
            example:
              name: "John Doe"
              email: "johndoe@email.com"
              passw: "password123"
              role: "usuario"
      responses:
        "200":
          description: Lista de Usuarios
          content:
            application/json:
              example:
                name: "John Doe"
                email: "johndoe@email.com"
                role: "usuario"
                createdAt: "2024-11-10T12:00:00Z"
        "400":
          description: El usuario ya existe
        "403":
          description: No autorizado
        "500":
          description: Error del servidor

  /api/admin/tasks:
    get:
      tags:
        - Admin
      summary: Obtener todas las tareas
      security:
        - JWTAuth: []
      responses:
        "200":
          description: Lista de Tareas
          content:
            application/json:
              example:
                name: "John Doe"
                email: "johndoe@email.com"
                role: "usuario"
                createdAt: "2024-11-10T12:00:00Z"
        "403":
          description: No autorizado
        "404":
          description: No existen tareas
        "500":
          description: Error del servidor
